create table "Player" (
  id            bigint generated by default as identity primary key,
  name          text not null,
  "emailAddress" text not null unique
);

create table "Game" (
  id   bigint generated by default as identity primary key,
  time timestamptz not null default now()
);

create table "PlayerGame" (
  id        bigint generated by default as identity primary key,
  "gameId"   bigint not null references "Game"(id) on delete cascade,
  "playerId" bigint not null references "Player"(id) on delete cascade,
  score     integer not null default 0
);

grant all on "Player", "Game", "PlayerGame" to anon, authenticated, service_role;
grant usage, select on all sequences in schema public to anon, authenticated, service_role;
